import { z } from 'zod';
import { defineTool, type ToolContext } from '../../../shared/tool';
import { toolRegistry } from './registry';
import { createLogger } from '../logger';

const log = createLogger('spawn_teammate');

const SpawnTeammateSchema = z.object({
  name: z.string().describe('Unique name for the teammate'),
  role: z.string().describe('Role description (e.g., "frontend developer")'),
  prompt: z.string().describe('System prompt generated by the team lead'),
  tools: z.array(z.string()).optional().describe('Allowed tool names'),
});

let teammateManager: TeammateManagerInterface | null = null;

export interface TeammateManagerInterface {
  spawnTeammate(config: {
    name: string;
    role: string;
    systemPrompt: string;
    allowedTools: string[];
    workingDir: string;
    leadSessionId: string;
  }): Promise<{ id: string; status: string }>;
}

export function setTeammateManager(manager: TeammateManagerInterface) {
  teammateManager = manager;
}

export const spawnTeammateTool = defineTool({
  name: 'spawn_teammate',
  description: `Create a persistent teammate that can handle tasks independently.

The teammate:
- Has its own conversation context
- Can receive and send messages
- Has a persistent inbox for communication
- Runs independently until shutdown

Use this for complex tasks that benefit from dedicated specialists.`,
  parameters: SpawnTeammateSchema,
  execute: async (
    params: z.infer<typeof SpawnTeammateSchema>,
    context: ToolContext
  ) => {
    if (!teammateManager) {
      return {
        success: false,
        output: 'Error: Teammate manager not available',
        error: 'Teammate manager not initialized',
      };
    }

    if (!context.sessionId) {
      return {
        success: false,
        output: 'Error: No session context',
        error: 'Missing session ID',
      };
    }

    try {
      const result = await teammateManager.spawnTeammate({
        name: params.name,
        role: params.role,
        systemPrompt: params.prompt,
        allowedTools: params.tools || [],
        workingDir: context.workingDir,
        leadSessionId: context.sessionId,
      });

      log.info(`Spawned teammate: ${params.name} (${result.id})`);

      return {
        success: true,
        output: `Teammate "${params.name}" created successfully.\nID: ${result.id}\nStatus: ${result.status}`,
      };
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      log.error('Failed to spawn teammate:', errorMsg);
      return {
        success: false,
        output: `Failed to spawn teammate: ${errorMsg}`,
        error: errorMsg,
      };
    }
  },
});

toolRegistry.register(spawnTeammateTool);
